name: tesla
version: 0.2.2
description: Proxy for accessing the Tesla Owners API.
author: Jason Daly <lyceel@gmail.com>
environment:
    sdk: '>=2.12.0 <3.0.0'
dependencies:
    ansicolor: '>=2.0.0 <3.0.0'
    args: '>=2.4.0 <3.0.0'
    async: '>=2.10.0 <3.0.0'
    collection: '>=1.17.0 <2.0.0'
    http: '>=0.13.0 <1.0.0'
    intl: '>=0.18.0 <1.0.0'
