const categoryNames = <String, String>{
  'C_MODEL': 'Tesla Model',
  'C_MFG_INTRO': 'Design Refresh',
  'C_TRIM': 'Trim Version',
  'C_INTL': 'Region Spec',
  'C_BAT': 'Battery',
  'C_BAT_FIRMWARE': 'Battery Firmware Limit',
  'C_MOTOR': 'Motor',
  'C_DRIVE': 'Drive Orientation',
  'C_PERF': 'Performance Options',
  'C_EXTCOL': 'Exterior Color',
  'C_RF': 'Roof',
  'C_WT': 'Wheels',
  'C_INTPKG_BASE': 'Base Interior Package',
  'C_INTPKG_VEGAN': 'Vegan Interior Package',
  'C_INTDECOR': 'Interior Decor',
  'C_INT_NOW_DEFAULT_OPTS': 'Included Interior Options',
  'C_STDEQ': 'Standard Equipment',
  'C_OPTS': 'Options',
  'C_CHG_INSTALL': 'Home Charging Installation',
  'C_CHG_SUPER': 'Supercharging',
};

const optionDecoder = <String, Map<String, String>>{
  'AD02': {'name': 'NEMA 14-50', 'category': 'C_OPTS'},
  'AD04': {'name': 'European 3-Phase', 'category': 'C_OPTS'},
  'AD05': {'name': 'European 3-Phase, IT', 'category': 'C_OPTS'},
  'AD06': {'name': 'Schuko (1 phase, 230V 13A)', 'category': 'C_OPTS'},
  'AD07': {'name': 'Red IEC309 (3 phase, 400V 16A)', 'category': 'C_OPTS'},
  'ADPX2': {'name': 'Type 2 Public Charging Connector', 'category': 'C_OPTS'},
  'ADX8': {'name': 'Blue IEC309 (1 phase, 230V 32A)', 'category': 'C_OPTS'},
  'AF00': {'name': 'No HEPA Filter', 'category': 'C_OPTS'},
  'AF02': {'name': 'HEPA Filter', 'category': 'C_OPTS'},
  'AH00': {'name': 'No Accessory Hitch', 'category': 'C_OPTS'},
  'APE1': {'name': 'Enhanced Autopilot', 'category': 'C_OPTS'},
  'APF0': {'name': 'Autopilot Firmware 2.0 Base', 'category': 'C_OPTS'},
  'APF1': {'name': 'Autopilot Firmware 2.0 Enhanced', 'category': 'C_OPTS'},
  'APF2': {'name': 'Full Self-Driving Capability', 'category': 'C_OPTS'},
  'APH0': {'name': 'Autopilot 2.0 Hardware', 'category': 'C_OPTS'},
  'APH2': {'name': 'Autopilot 2.0 Hardware', 'category': 'C_OPTS'},
  'APH3': {'name': 'Autopilot 2.5 Hardware', 'category': 'C_OPTS'},
  'APPA': {'name': 'Autopilot 1.0 Hardware', 'category': 'C_OPTS'},
  'APPB': {'name': 'Enhanced Autopilot', 'category': 'C_OPTS'},
  'AU00': {'name': 'No Audio Package', 'category': 'C_OPTS'},
  'AU01': {'name': 'Ultra High Fidelity Sound', 'category': 'C_OPTS'},
  'BC0R': {'name': 'Tesla Red Brake Calipers', 'category': 'C_PERF'},
  'BCMB': {'name': 'Black Brake Calipers', 'category': 'C_PERF'},
  'BP00': {'name': 'No Ludicrous', 'category': 'C_PERF'},
  'BP01': {'name': 'Ludicrous Speed Upgrade', 'category': 'C_PERF'},
  'BR00': {'name': 'No Battery Firmware Limit', 'category': 'C_BAT_FIRMWARE'},
  'BR03': {
    'name': 'Battery Firmware Limit (60kWh)',
    'category': 'C_BAT_FIRMWARE'
  },
  'BR05': {
    'name': 'Battery Firmware Limit (75kWh)',
    'category': 'C_BAT_FIRMWARE'
  },
  'BS00': {'name': 'General Production Flag', 'category': 'C_OPTS'},
  'BS01': {'name': 'Special Production Flag', 'category': 'C_OPTS'},
  'BT37': {'name': '75 kWh (Model 3)', 'category': 'C_BAT'},
  'BT40': {'name': '40 kWh', 'category': 'C_BAT'},
  'BT60': {'name': '60 kWh', 'category': 'C_BAT'},
  'BT70': {'name': '70 kWh', 'category': 'C_BAT'},
  'BT85': {'name': '85 kWh', 'category': 'C_BAT'},
  'BTX4': {'name': '90 kWh', 'category': 'C_BAT'},
  'BTX5': {'name': '75 kWh', 'category': 'C_BAT'},
  'BTX6': {'name': '100 kWh', 'category': 'C_BAT'},
  'BTX7': {'name': '75 kWh', 'category': 'C_BAT'},
  'BTX8': {'name': '85 kWh', 'category': 'C_BAT'},
  'CC04': {'name': 'Seven Seat Interior', 'category': 'C_OPTS'},
  'CDM0': {'name': 'No CHAdeMO Charging Adaptor', 'category': 'C_OPTS'},
  'CH00': {'name': 'Standard Charger (40 Amp)', 'category': 'C_OPTS'},
  'CH01': {'name': 'Dual Chargers (80 Amp)', 'category': 'C_OPTS'},
  'CH04': {'name': '72 Amp Charger (Model S/X)', 'category': 'C_OPTS'},
  'CH05': {'name': '48 Amp Charger (Model S/X)', 'category': 'C_OPTS'},
  'CH07': {'name': '48 Amp Charger (Model 3)', 'category': 'C_OPTS'},
  'COL0': {'name': 'Signature', 'category': 'C_EXTCOL'},
  'COL1': {'name': 'Solid', 'category': 'C_EXTCOL'},
  'COL2': {'name': 'Metallic', 'category': 'C_EXTCOL'},
  'COL3': {'name': 'Tesla Multi-Coat', 'category': 'C_EXTCOL'},
  'COUS': {'name': 'US Vehicle?', 'category': 'C_INTL'},
  'CW00': {'name': 'No Cold Weather Package', 'category': 'C_OPTS'},
  'CW02': {'name': 'Subzero Weather Package', 'category': 'C_OPTS'},
  'DA00': {'name': 'No Autopilot', 'category': 'C_OPTS'},
  'DA01': {'name': 'Active Safety (ACC,LDW,SA)', 'category': 'C_OPTS'},
  'DA02': {'name': 'Autopilot Convenience Features', 'category': 'C_OPTS'},
  'DCF0': {
    'name': 'Autopilot Convenience Features (DCF0)',
    'category': 'C_OPTS'
  },
  'DRLH': {'name': 'Left Hand Drive', 'category': 'C_DRIVE'},
  'DRRH': {'name': 'Right Hand Drive', 'category': 'C_DRIVE'},
  'DSH5': {'name': 'PUR Dash Pad', 'category': 'C_OPTS'},
  'DSH7': {'name': 'Alcantara Dashboard Accents', 'category': 'C_OPTS'},
  'DU00': {'name': 'Drive Unit - IR', 'category': 'C_OPTS'},
  'DU01': {'name': 'Drive Unit - Infineon', 'category': 'C_OPTS'},
  'DV2W': {'name': 'Rear-Wheel Drive', 'category': 'C_MOTOR'},
  'DV4W': {'name': 'All-Wheel Drive', 'category': 'C_MOTOR'},
  'FG00': {'name': 'No Exterior Lighting Package', 'category': 'C_OPTS'},
  'FG01': {'name': 'Exterior Lighting Package', 'category': 'C_OPTS'},
  'FG02': {'name': 'Exterior Lighting Package', 'category': 'C_OPTS'},
  'FMP6': {'name': 'FMP6', 'category': 'C_OPTS'},
  'FR01': {'name': 'Base Front Row', 'category': 'C_OPTS'},
  'FR03': {'name': 'FR03', 'category': 'C_OPTS'},
  'FR04': {'name': 'FR04', 'category': 'C_OPTS'},
  'HC00': {
    'name': 'No Home Charging installation',
    'category': 'C_CHG_INSTALL'
  },
  'HC01': {'name': 'Home Charging Installation', 'category': 'C_CHG_INSTALL'},
  'HP00': {'name': 'No HPWC Ordered', 'category': 'C_CHG_SUPER'},
  'HP01': {'name': 'HPWC Ordered', 'category': 'C_CHG_SUPER'},
  'IDBA': {'name': 'Dark Ash Wood Decor', 'category': 'C_INTDECOR'},
  'IDBO': {'name': 'Figured Ash Wood Decor', 'category': 'C_INTDECOR'},
  'IDCF': {'name': 'Carbon Fiber Decor', 'category': 'C_INTDECOR'},
  'IDOM': {'name': 'Matte Obeche Wood Decor', 'category': 'C_INTDECOR'},
  'IDOG': {'name': 'Gloss Obeche Wood Decor', 'category': 'C_INTDECOR'},
  'IDLW': {'name': 'Lacewood Decor', 'category': 'C_INTDECOR'},
  'IDPB': {'name': 'Piano Black Decor', 'category': 'C_INTDECOR'},
  'INBBW': {'name': 'White', 'category': 'C_INTPKG_BASE'},
  'INBFP': {'name': 'Classic Black', 'category': 'C_INTPKG_BASE'},
  'INBPP': {'name': 'Black', 'category': 'C_INTPKG_BASE'},
  'INBTB': {'name': 'Multi-Pattern Black', 'category': 'C_INTPKG_BASE'},
  'INLPC': {'name': 'Cream', 'category': 'C_INTPKG_BASE'},
  'INLPP': {'name': 'Black / Light Headliner', 'category': 'C_INTPKG_BASE'},
  'INWPT': {'name': 'Tan Interior', 'category': 'C_INTPKG_BASE'},
  'IVBPP': {'name': 'All Black Interior', 'category': 'C_INTPKG_VEGAN'},
  'IVBSW': {'name': 'Ultra White Interior', 'category': 'C_INTPKG_VEGAN'},
  'IVBTB': {'name': 'All Black Interior', 'category': 'C_INTPKG_VEGAN'},
  'IVLPC': {'name': 'Vegan Cream', 'category': 'C_INTPKG_VEGAN'},
  'IX00': {
    'name': 'No Extended Nappa Leather Trim',
    'category': 'C_INTPKG_BASE'
  },
  'IX01': {'name': 'Extended Nappa Leather Trim', 'category': 'C_INTPKG_BASE'},
  'LLP1': {'name': 'LLP1', 'category': 'C_OPTS'},
  'LP01': {
    'name': 'Premium Interior Lighting',
    'category': 'C_INT_NOW_DEFAULT_OPTS'
  },
  'LT00': {'name': 'Vegan interior', 'category': 'C_OPTS'},
  'LT01': {'name': 'Standard interior', 'category': 'C_OPTS'},
  'LT1B': {'name': 'LT1B', 'category': 'C_OPTS'},
  'LT3W': {'name': 'LT3W', 'category': 'C_OPTS'},
  'LT4B': {'name': 'LT4B', 'category': 'C_OPTS'},
  'LT4C': {'name': 'LT4C', 'category': 'C_OPTS'},
  'LT4W': {'name': 'LT4W', 'category': 'C_OPTS'},
  'LT5C': {'name': 'LT5C', 'category': 'C_OPTS'},
  'LT5P': {'name': 'LT5P', 'category': 'C_OPTS'},
  'MDLS': {'name': 'Model S', 'category': 'C_MODEL'},
  'MDLX': {'name': 'Model X', 'category': 'C_MODEL'},
  'ME02': {'name': 'Memory Seats', 'category': 'C_STDEQ'},
  'MI00': {'name': '2015 Production Refresh', 'category': 'C_MFG_INTRO'},
  'MI01': {'name': '2016 Production Refresh', 'category': 'C_MFG_INTRO'},
  'MI02': {'name': '2017 Production Refresh', 'category': 'C_MFG_INTRO'},
  'PA00': {'name': 'No Paint Armor', 'category': 'C_OPTS'},
  'PBCW': {'name': 'Catalina White', 'category': 'C_EXTCOL'},
  'PBSB': {'name': 'Sierra Black', 'category': 'C_EXTCOL'},
  'PBT8': {'name': 'Performance 85kWh', 'category': 'C_PERF'},
  'PF00': {'name': 'No Performance Legacy Package', 'category': 'C_OPTS'},
  'PF01': {'name': 'Performance Legacy Package', 'category': 'C_OPTS'},
  'PI00': {'name': 'No Premium Interior', 'category': 'C_OPTS'},
  'PI01': {'name': 'Premium Upgrades Package', 'category': 'C_OPTS'},
  'PK00': {'name': 'LEGACY No Parking Sensors', 'category': 'C_STDEQ'},
  'PMAB': {'name': 'Anza Brown Metallic', 'category': 'C_EXTCOL'},
  'PMBL': {'name': 'Obsidian Black Multi-Coat', 'category': 'C_EXTCOL'},
  'PMMB': {'name': 'Monterey Blue Metallic', 'category': 'C_EXTCOL'},
  'PMMR': {'name': 'Multi-Coat Red', 'category': 'C_EXTCOL'},
  'PMNG': {'name': 'Midnight Silver Metallic', 'category': 'C_EXTCOL'},
  'PMSG': {'name': 'Sequoia Green Metallic', 'category': 'C_EXTCOL'},
  'PMSS': {'name': 'San Simeon Silver Metallic', 'category': 'C_EXTCOL'},
  'PMTG': {'name': 'Dolphin Grey Metallic', 'category': 'C_EXTCOL'},
  'PPMR': {'name': 'Muir Red Multi-Coat', 'category': 'C_EXTCOL'},
  'PPSB': {'name': 'Deep Blue Metallic', 'category': 'C_EXTCOL'},
  'PPSR': {'name': 'Signature Red', 'category': 'C_EXTCOL'},
  'PPSW': {'name': 'Shasta Pearl White Multi-Coat', 'category': 'C_EXTCOL'},
  'PPTI': {'name': 'Titanium Metallic', 'category': 'C_EXTCOL'},
  'PS00': {'name': 'No Parcel Shelf', 'category': 'C_STDEQ'},
  'PS01': {'name': 'Parcel Shelf', 'category': 'C_STDEQ'},
  'PX00': {'name': 'No Performance Plus Package', 'category': 'C_PERF'},
  'PX01': {'name': 'Performance Plus', 'category': 'C_PERF'},
  'PX6D': {'name': 'Zero to 60 in 2.5 sec', 'category': 'C_PERF'},
  'P85D': {'name': 'P85D', 'category': 'C_PERF'},
  'QNET': {'name': 'Tan NextGen', 'category': 'C_INTBASE'},
  'QPMP': {'name': 'Black seats', 'category': 'C_INTBASE'},
  'QTBW': {'name': 'White Premium Seats', 'category': 'C_INTBASE'},
  'QTPC': {'name': 'Cream Premium Seats', 'category': 'C_INTBASE'},
  'QTPP': {'name': 'Black Premium Seats', 'category': 'C_INTBASE'},
  'QTPT': {'name': 'Tan Premium Seats', 'category': 'C_INTBASE'},
  'QTTB': {'name': 'Multi-Pattern Black Seats', 'category': 'C_INTBASE'},
  'QVBM': {'name': 'Multi-Pattern Black Seats', 'category': 'C_INTBASE'},
  'QVPC': {'name': 'Vegan Cream Seats', 'category': 'C_INTBASE'},
  'QVPP': {'name': 'Vegan Cream Seats', 'category': 'C_INTBASE'},
  'QVSW': {'name': 'White Tesla Seats', 'category': 'C_INTBASE'},
  'RCX0': {'name': 'No Rear Console', 'category': 'C_OPTS'},
  'RENA': {'name': 'Region: North America', 'category': 'C_INTL'},
  'RENC': {'name': 'Region: Canada', 'category': 'C_INTL'},
  'REEU': {'name': 'Region: Europe', 'category': 'C_INTL'},
  'RF3G': {'name': 'Model 3 Glass Roof', 'category': 'C_RF'},
  'RFBK': {'name': 'Black Roof', 'category': 'C_RF'},
  'RFBC': {'name': 'Body Color Roof', 'category': 'C_RF'},
  'RFFG': {'name': 'Glass Roof', 'category': 'C_RF'},
  'RFP0': {'name': 'All Glass Panoramic Roof', 'category': 'C_RF'},
  'RFP2': {'name': 'Sunroof', 'category': 'C_RF'},
  'RFPX': {'name': 'Model X Roof', 'category': 'C_RF'},
  'S02P': {'name': 'S02P', 'category': 'C_OPTS'},
  'S31B': {'name': 'S31B', 'category': 'C_OPTS'},
  'S32C': {'name': 'S32C', 'category': 'C_OPTS'},
  'S32P': {'name': 'S32P', 'category': 'C_OPTS'},
  'S32W': {'name': 'S32W', 'category': 'C_OPTS'},
  'SC00': {'name': 'No Supercharging', 'category': 'C_CHG_SUPER'},
  'SC01': {'name': 'Supercharging Enabled', 'category': 'C_CHG_SUPER'},
  'SC04': {'name': 'Pay Per Use Supercharging', 'category': 'C_CHG_SUPER'},
  'SC05': {'name': 'Free Supercharging', 'category': 'C_CHG_SUPER'},
  'SP00': {'name': 'No Security Package', 'category': 'C_OPTS'},
  'SR01': {'name': 'Standard 2nd row', 'category': 'C_OPTS'},
  'SR06': {'name': 'Seven Seat Interior', 'category': 'C_OPTS'},
  'SR07': {'name': 'Standard 2nd row', 'category': 'C_OPTS'},
  'ST00': {'name': 'Non-leather Steering Wheel', 'category': 'C_OPTS'},
  'ST01': {'name': 'Non-heated Leather Steering Wheel', 'category': 'C_OPTS'},
  'SU00': {'name': 'Standard Suspension', 'category': 'C_OPTS'},
  'SU01': {'name': 'Smart Air Suspension', 'category': 'C_OPTS'},
  'TIC4': {'name': 'All-Season Tires', 'category': 'C_OPTS'},
  'TM00': {'name': 'General Production Trim', 'category': 'C_TRIM'},
  'TM02': {'name': 'General Production Signature Trim', 'category': 'C_TRIM'},
  'TM0A': {'name': 'ALPHA PRE-PRODUCTION NON-SALEABLE', 'category': 'C_TRIM'},
  'TM0B': {'name': 'BETA PRE-PRODUCTION NON-SALEABLE', 'category': 'C_TRIM'},
  'TM0C': {'name': 'PRE-PRODUCTION SALEABLE', 'category': 'C_TRIM'},
  'TP01': {'name': 'Tech Package - No Autopilot', 'category': 'C_OPTS'},
  'TP02': {'name': 'Tech Package with Autopilot', 'category': 'C_OPTS'},
  'TP03': {
    'name': 'Tech Package with Enhanced Autopilot',
    'category': 'C_OPTS'
  },
  'TR00': {'name': 'No Third Row Seat', 'category': 'C_OPTS'},
  'TR01': {'name': 'Third Row Seating', 'category': 'C_OPTS'},
  'TRA1': {'name': 'Third Row HVAC', 'category': 'C_OPTS'},
  'TW01': {'name': 'Towing Package', 'category': 'C_OPTS'},
  'UM01': {
    'name': 'Universal Mobile Charger - US Port (Single)',
    'category': 'C_OPTS'
  },
  'UTAB': {'name': 'Black Alcantara Headliner', 'category': 'C_INT_HEADLINER'},
  'UTAW': {'name': 'Light Headliner', 'category': 'C_INT_HEADLINER'},
  'UTPB': {'name': 'Dark Headliner', 'category': 'C_INT_HEADLINER'},
  'UTSB': {'name': 'Dark Headliner', 'category': 'C_INT_HEADLINER'},
  'WT20': {'name': '20" Silver Slipstream Wheels', 'category': 'C_WT'},
  'WTAS': {'name': '19" Silver Slipstream Wheels', 'category': 'C_WT'},
  'WTDS': {'name': '19" Grey Slipstream Wheels', 'category': 'C_WT'},
  'WTSG': {'name': '21" Turbine Wheels', 'category': 'C_WT'},
  'WTSS': {'name': '21" Turbine Wheels', 'category': 'C_WT'},
  'WTTB': {'name': '19" Cyclone Wheels', 'category': 'C_WT'},
  'WTW4': {'name': '19" Winter Tire Set', 'category': 'C_OPTS'},
  'WTW5': {'name': '21" Winter Tire Set', 'category': 'C_OPTS'},
  'WTX1': {'name': '19" Michelin Primacy Tire Upgrade', 'category': 'C_OPTS'},
  'WXW4': {'name': 'No 19" Winter Tire Set', 'category': 'C_OPTS'},
  'WXW5': {'name': 'No 21" Winter Tire Set', 'category': 'C_OPTS'},
  'X001': {'name': 'Override: Power Liftgate', 'category': 'C_STDEQ'},
  'X003': {'name': 'Maps & Navigation', 'category': 'C_STDEQ'},
  'X004': {'name': 'Override: No Navigation', 'category': 'C_OPTS'},
  'X007': {'name': 'Daytime running lights', 'category': 'C_OPTS'},
  'X010': {'name': 'Base Mirrors', 'category': 'C_OPTS'},
  'X011': {'name': 'Override: Homelink', 'category': 'C_OPTS'},
  'X012': {'name': 'Override: No Homelink', 'category': 'C_STDEQ'},
  'X013': {'name': 'Override: Satellite Radio', 'category': 'C_OPTS'},
  'X014': {'name': 'Override: No Satellite Radio', 'category': 'C_OPTS'},
  'X019': {'name': 'Carbon Fiber Spoiler', 'category': 'C_OPTS'},
  'X020': {'name': 'No Performance Exterior', 'category': 'C_PERF'},
  'X021': {'name': 'No Spoiler', 'category': 'C_OPTS'},
  'X024': {'name': 'Performance Package', 'category': 'C_PERF'},
  'X025': {'name': 'No Performance Package', 'category': 'C_PERF'},
  'X027': {'name': 'Lighted Door Handles', 'category': 'C_STDEQ'},
  'X028': {'name': 'Battery Badge', 'category': 'C_OPTS'},
  'X029': {'name': 'Remove Battery Badge', 'category': 'C_OPTS'},
  'X030': {'name': 'Override: No Passive Entry Pkg', 'category': 'C_OPTS'},
  'X031': {'name': 'Keyless Entry', 'category': 'C_STDEQ'},
  'X037': {'name': 'Powerfolding Mirrors', 'category': 'C_STDEQ'},
  'X039': {'name': 'DAB Radio', 'category': 'C_OPTS'},
  'X040': {'name': 'No DAB Radio', 'category': 'C_OPTS'},
  'X043': {'name': 'No Phone Dock Kit', 'category': 'C_OPTS'},
  'X044': {'name': 'Phone Dock Kit', 'category': 'C_OPTS'},
  'YF00': {'name': 'No Yacht Floor', 'category': 'C_INT_NOW_DEFAULT_OPTS'},
  'YF01': {
    'name': 'Matching Yacht Floor',
    'category': 'C_INT_NOW_DEFAULT_OPTS'
  },
  'YFCC': {'name': 'YFCC', 'category': 'C_OPTS'},
  'YFFC': {'name': 'Integrated Center Console', 'category': 'C_OPTS'}
};
