const categoryNames = const <String, String>{
  "C_MODEL": "Tesla Model",
  "C_MFG_INTRO": "Design Refresh",
  "C_TRIM": "Trim Version",
  "C_INTL": "Region Spec",
  "C_BAT": "Battery",
  "C_BAT_FIRMWARE": "Battery Firmware Limit",
  "C_MOTOR": "Motor",
  "C_DRIVE": "Drive Orientation",
  "C_PERF": "Performance Options",
  "C_EXTCOL": "Exterior Color",
  "C_RF": "Roof",
  "C_WT": "Wheels",
  "C_INTPKG_BASE": "Base Interior Package",
  "C_INTPKG_VEGAN": "Vegan Interior Package",
  "C_INTDECOR": "Interior Decor",
  "C_INT_NOW_DEFAULT_OPTS": "Included Interior Options",
  "C_STDEQ": "Standard Equipment",
  "C_OPTS": "Options",
  "C_CHG_INSTALL": "Home Charging Installation",
  "C_CHG_SUPER": "Supercharging",
};

const optionDecoder = const <String, Map<String, String>>{
  "AD02": const {"name": "NEMA 14-50", "category": "C_OPTS"},
  "AD04": const {"name": "European 3-Phase", "category": "C_OPTS"},
  "AD05": const {"name": "European 3-Phase, IT", "category": "C_OPTS"},
  "AD06": const {"name": "Schuko (1 phase, 230V 13A)", "category": "C_OPTS"},
  "AD07": const {
    "name": "Red IEC309 (3 phase, 400V 16A)",
    "category": "C_OPTS"
  },
  "ADPX2": const {
    "name": "Type 2 Public Charging Connector",
    "category": "C_OPTS"
  },
  "ADX8": const {
    "name": "Blue IEC309 (1 phase, 230V 32A)",
    "category": "C_OPTS"
  },
  "AF00": const {"name": "No HEPA Filter?", "category": "C_OPTS"},
  "AF02": const {"name": "HEPA Filter", "category": "C_OPTS"},
  "AH00": const {"name": "No Accessory Hitch", "category": "C_OPTS"},
  "APE1": const {"name": "Enhanced Autopilot", "category": "C_OPTS"},
  "APF0": const {"name": "Autopilot Firmware 2.0 Base", "category": "C_OPTS"},
  "APF1": const {
    "name": "Autopilot Firmware 2.0 Enhanced",
    "category": "C_OPTS"
  },
  "APF2": const {"name": "Full Self-Driving Capability", "category": "C_OPTS"},
  "APH0": const {"name": "Autopilot 2.0 Hardware?", "category": "C_OPTS"},
  "APH2": const {"name": "Autopilot 2.0 Hardware?", "category": "C_OPTS"},
  "APH3": const {"name": "Autopilot 2.5 Hardware?", "category": "C_OPTS"},
  "APPA": const {"name": "Autopilot Hardware 1", "category": "C_OPTS"},
  "APPB": const {"name": "Enhanced Autopilot", "category": "C_OPTS"},
  "AU00": const {"name": "No Audio Package", "category": "C_OPTS"},
  "AU01": const {"name": "Ultra High Fidelity Sound", "category": "C_OPTS"},
  "BC0R": const {"name": "Tesla Red Brake Calipers", "category": "C_PERF"},
  "BCMB": const {"name": "Black Brake Calipers", "category": "C_PERF"},
  "BP00": const {"name": "No Ludicrous", "category": "C_PERF"},
  "BP01": const {"name": "Ludicrous Speed Upgrade", "category": "C_PERF"},
  "BR00": const {
    "name": "No Battery Firmware Limit",
    "category": "C_BAT_FIRMWARE"
  },
  "BR03": const {
    "name": "Battery Firmware Limit (60kWh)",
    "category": "C_BAT_FIRMWARE"
  },
  "BR05": const {
    "name": "Battery Firmware Limit (75kWh)",
    "category": "C_BAT_FIRMWARE"
  },
  "BS00": const {"name": "General Production Flag", "category": "C_OPTS"},
  "BS01": const {"name": "Special Production Flag", "category": "C_OPTS"},
  "BT40": const {"name": "40 kWh", "category": "C_BAT"},
  "BT60": const {"name": "60 kWh", "category": "C_BAT"},
  "BT70": const {"name": "70 kWh", "category": "C_BAT"},
  "BT85": const {"name": "85 kWh", "category": "C_BAT"},
  "BTX4": const {"name": "90 kWh", "category": "C_BAT"},
  "BTX5": const {"name": "75 kWh", "category": "C_BAT"},
  "BTX6": const {"name": "100 kWh", "category": "C_BAT"},
  "BTX7": const {"name": "75 kWh", "category": "C_BAT"},
  "BTX8": const {"name": "85 kWh", "category": "C_BAT"},
  "CC04": const {"name": "Seven Seat Interior", "category": "C_OPTS"},
  "CDM0": const {"name": "No CHAdeMO Charging Adaptor", "category": "C_OPTS"},
  "CH00": const {"name": "Standard Charger (40 Amp)", "category": "C_OPTS"},
  "CH01": const {"name": "Dual Chargers (80 Amp)", "category": "C_OPTS"},
  "CH04": const {"name": "72 Amp Charger", "category": "C_OPTS"},
  "CH05": const {"name": "48 Amp Charger", "category": "C_OPTS"},
  "COL0": const {"name": "Signature", "category": "C_EXTCOL"},
  "COL1": const {"name": "Solid", "category": "C_EXTCOL"},
  "COL2": const {"name": "Metallic", "category": "C_EXTCOL"},
  "COL3": const {"name": "Tesla Multi-Coat", "category": "C_EXTCOL"},
  "COUS": const {"name": "US Vehicle?", "category": "C_INTL"},
  "CW00": const {"name": "No Cold Weather Package", "category": "C_OPTS"},
  "CW02": const {"name": "Subzero Weather Package", "category": "C_OPTS"},
  "DA00": const {"name": "No Autopilot", "category": "C_OPTS"},
  "DA01": const {"name": "Active Safety (ACC,LDW,SA)", "category": "C_OPTS"},
  "DA02": const {
    "name": "Autopilot Convenience Features",
    "category": "C_OPTS"
  },
  "DCF0": const {
    "name": "Autopilot Convenience Features (DCF0)",
    "category": "C_OPTS"
  },
  "DRLH": const {"name": "Left Hand Drive", "category": "C_DRIVE"},
  "DRRH": const {"name": "Right Hand Drive", "category": "C_DRIVE"},
  "DSH5": const {"name": "PUR Dash Pad", "category": "C_OPTS"},
  "DSH7": const {"name": "Alcantara Dashboard Accents", "category": "C_OPTS"},
  "DU00": const {"name": "Drive Unit - IR", "category": "C_OPTS"},
  "DU01": const {"name": "Drive Unit - Infineon", "category": "C_OPTS"},
  "DV2W": const {"name": "Rear-Wheel Drive", "category": "C_MOTOR"},
  "DV4W": const {"name": "All-Wheel Drive", "category": "C_MOTOR"},
  "FG00": const {"name": "No Exterior Lighting Package", "category": "C_OPTS"},
  "FG01": const {"name": "Exterior Lighting Package", "category": "C_OPTS"},
  "FG02": const {"name": "Exterior Lighting Package", "category": "C_OPTS"},
  "FMP6": const {"name": "FMP6", "category": "C_OPTS"},
  "FR01": const {"name": "Base Front Row", "category": "C_OPTS"},
  "FR03": const {"name": "FR03", "category": "C_OPTS"},
  "FR04": const {"name": "FR04", "category": "C_OPTS"},
  "HC00": const {
    "name": "No Home Charging installation",
    "category": "C_CHG_INSTALL"
  },
  "HC01": const {
    "name": "Home Charging Installation",
    "category": "C_CHG_INSTALL"
  },
  "HP00": const {"name": "No HPWC Ordered", "category": "C_CHG_SUPER"},
  "HP01": const {"name": "HPWC Ordered", "category": "C_CHG_SUPER"},
  "IDBA": const {"name": "Dark Ash Wood Decor", "category": "C_INTDECOR"},
  "IDBO": const {"name": "Figured Ash Wood Decor", "category": "C_INTDECOR"},
  "IDCF": const {"name": "Carbon Fiber Decor", "category": "C_INTDECOR"},
  "IDOM": const {"name": "Matte Obeche Wood Decor", "category": "C_INTDECOR"},
  "IDOG": const {"name": "Gloss Obeche Wood Decor", "category": "C_INTDECOR"},
  "IDLW": const {"name": "Lacewood Decor", "category": "C_INTDECOR"},
  "IDPB": const {"name": "Piano Black Decor", "category": "C_INTDECOR"},
  "INBBW": const {"name": "White", "category": "C_INTPKG_BASE"},
  "INBFP": const {"name": "Classic Black", "category": "C_INTPKG_BASE"},
  "INBPP": const {"name": "Black", "category": "C_INTPKG_BASE"},
  "INBTB": const {"name": "Multi-Pattern Black", "category": "C_INTPKG_BASE"},
  "INLPC": const {"name": "Cream", "category": "C_INTPKG_BASE"},
  "INLPP": const {
    "name": "Black / Light Headliner",
    "category": "C_INTPKG_BASE"
  },
  "INWPT": const {"name": "Tan Interior", "category": "C_INTPKG_BASE"},
  "IVBPP": const {"name": "All Black Interior", "category": "C_INTPKG_VEGAN"},
  "IVBSW": const {"name": "Ultra White Interior", "category": "C_INTPKG_VEGAN"},
  "IVBTB": const {"name": "All Black Interior", "category": "C_INTPKG_VEGAN"},
  "IVLPC": const {"name": "Vegan Cream", "category": "C_INTPKG_VEGAN"},
  "IX00": const {
    "name": "No Extended Nappa Leather Trim",
    "category": "C_INTPKG_BASE"
  },
  "IX01": const {
    "name": "Extended Nappa Leather Trim",
    "category": "C_INTPKG_BASE"
  },
  "LLP1": const {"name": "LLP1", "category": "C_OPTS"},
  "LP01": const {
    "name": "Premium Interior Lighting",
    "category": "C_INT_NOW_DEFAULT_OPTS"
  },
  "LT00": const {"name": "Vegan interior", "category": "C_OPTS"},
  "LT01": const {"name": "Standard interior", "category": "C_OPTS"},
  "LT1B": const {"name": "LT1B", "category": "C_OPTS"},
  "LT3W": const {"name": "LT3W", "category": "C_OPTS"},
  "LT4B": const {"name": "LT4B", "category": "C_OPTS"},
  "LT4C": const {"name": "LT4C", "category": "C_OPTS"},
  "LT4W": const {"name": "LT4W", "category": "C_OPTS"},
  "LT5C": const {"name": "LT5C", "category": "C_OPTS"},
  "LT5P": const {"name": "LT5P", "category": "C_OPTS"},
  "MDLS": const {"name": "Model S", "category": "C_MODEL"},
  "MDLX": const {"name": "Model X", "category": "C_MODEL"},
  "ME02": const {"name": "Memory Seats", "category": "C_STDEQ"},
  "MI00": const {"name": "2015 Production Refresh", "category": "C_MFG_INTRO"},
  "MI01": const {"name": "2016 Production Refresh", "category": "C_MFG_INTRO"},
  "MI02": const {"name": "2017 Production Refresh", "category": "C_MFG_INTRO"},
  "PA00": const {"name": "No Paint Armor", "category": "C_OPTS"},
  "PBCW": const {"name": "Catalina White", "category": "C_EXTCOL"},
  "PBSB": const {"name": "Sierra Black", "category": "C_EXTCOL"},
  "PBT8": const {"name": "Performance 85kWh", "category": "C_PERF"},
  "PF00": const {"name": "No Performance Legacy Package", "category": "C_OPTS"},
  "PF01": const {"name": "Performance Legacy Package", "category": "C_OPTS"},
  "PI00": const {"name": "No Premium Interior", "category": "C_OPTS"},
  "PI01": const {"name": "Premium Upgrades Package", "category": "C_OPTS"},
  "PK00": const {"name": "LEGACY No Parking Sensors", "category": "C_STDEQ"},
  "PMAB": const {"name": "Anza Brown Metallic", "category": "C_EXTCOL"},
  "PMBL": const {"name": "Obsidian Black Multi-Coat", "category": "C_EXTCOL"},
  "PMMB": const {"name": "Monterey Blue Metallic", "category": "C_EXTCOL"},
  "PMMR": const {"name": "Multi-Coat Red", "category": "C_EXTCOL"},
  "PMNG": const {"name": "Midnight Silver Metallic", "category": "C_EXTCOL"},
  "PMSG": const {"name": "Sequoia Green Metallic", "category": "C_EXTCOL"},
  "PMSS": const {"name": "San Simeon Silver Metallic", "category": "C_EXTCOL"},
  "PMTG": const {"name": "Dolphin Grey Metallic", "category": "C_EXTCOL"},
  "PPMR": const {"name": "Muir Red Multi-Coat", "category": "C_EXTCOL"},
  "PPSB": const {"name": "Deep Blue Metallic", "category": "C_EXTCOL"},
  "PPSR": const {"name": "Signature Red", "category": "C_EXTCOL"},
  "PPSW": const {
    "name": "Shasta Pearl White Multi-Coat",
    "category": "C_EXTCOL"
  },
  "PPTI": const {"name": "Titanium Metallic", "category": "C_EXTCOL"},
  "PS00": const {"name": "No Parcel Shelf", "category": "C_STDEQ"},
  "PS01": const {"name": "Parcel Shelf", "category": "C_STDEQ"},
  "PX00": const {"name": "No Performance Plus Package", "category": "C_PERF"},
  "PX01": const {"name": "Performance Plus", "category": "C_PERF"},
  "PX6D": const {"name": "Zero to 60 in 2.5 sec", "category": "C_PERF"},
  "P85D": const {"name": "P85D", "category": "C_PERF"},
  "QNET": const {"name": "Tan NextGen", "category": "C_INTBASE"},
  "QPMP": const {"name": "Black seats", "category": "C_INTBASE"},
  "QTBW": const {"name": "White Premium Seats", "category": "C_INTBASE"},
  "QTPC": const {"name": "Cream Premium Seats", "category": "C_INTBASE"},
  "QTPP": const {"name": "Black Premium Seats", "category": "C_INTBASE"},
  "QTPT": const {"name": "Tan Premium Seats", "category": "C_INTBASE"},
  "QTTB": const {"name": "Multi-Pattern Black Seats", "category": "C_INTBASE"},
  "QVBM": const {"name": "Multi-Pattern Black Seats", "category": "C_INTBASE"},
  "QVPC": const {"name": "Vegan Cream Seats", "category": "C_INTBASE"},
  "QVPP": const {"name": "Vegan Cream Seats", "category": "C_INTBASE"},
  "QVSW": const {"name": "White Tesla Seats", "category": "C_INTBASE"},
  "RCX0": const {"name": "No Rear Console", "category": "C_OPTS"},
  "RENA": const {"name": "Region: North America", "category": "C_INTL"},
  "RENC": const {"name": "Region: Canada", "category": "C_INTL"},
  "REEU": const {"name": "Region: Europe", "category": "C_INTL"},
  "RFBK": const {"name": "Black Roof", "category": "C_RF"},
  "RFBC": const {"name": "Body Color Roof", "category": "C_RF"},
  "RFFG": const {"name": "Glass Roof", "category": "C_RF"},
  "RFP0": const {"name": "All Glass Panoramic Roof", "category": "C_RF"},
  "RFP2": const {"name": "Sunroof", "category": "C_RF"},
  "RFPX": const {"name": "Model X Roof", "category": "C_RF"},
  "S02P": const {"name": "S02P", "category": "C_OPTS"},
  "S31B": const {"name": "S31B", "category": "C_OPTS"},
  "S32C": const {"name": "S32C", "category": "C_OPTS"},
  "S32P": const {"name": "S32P", "category": "C_OPTS"},
  "S32W": const {"name": "S32W", "category": "C_OPTS"},
  "SC00": const {"name": "No Supercharging", "category": "C_CHG_SUPER"},
  "SC01": const {"name": "Supercharging Enabled", "category": "C_CHG_SUPER"},
  "SC04": const {
    "name": "Pay Per Use Supercharging",
    "category": "C_CHG_SUPER"
  },
  "SC05": const {"name": "Free Supercharging", "category": "C_CHG_SUPER"},
  "SP00": const {"name": "No Security Package", "category": "C_OPTS"},
  "SR01": const {"name": "Standard 2nd row", "category": "C_OPTS"},
  "SR06": const {"name": "Seven Seat Interior", "category": "C_OPTS"},
  "SR07": const {"name": "Standard 2nd row", "category": "C_OPTS"},
  "ST00": const {"name": "Non-leather Steering Wheel", "category": "C_OPTS"},
  "ST01": const {
    "name": "Non-heated Leather Steering Wheel",
    "category": "C_OPTS"
  },
  "SU00": const {"name": "Standard Suspension", "category": "C_OPTS"},
  "SU01": const {"name": "Smart Air Suspension", "category": "C_OPTS"},
  "TIC4": const {"name": "All-Season Tires", "category": "C_OPTS"},
  "TM00": const {"name": "General Production Trim", "category": "C_TRIM"},
  "TM02": const {
    "name": "General Production Signature Trim",
    "category": "C_TRIM"
  },
  "TM0A": const {
    "name": "ALPHA PRE-PRODUCTION NON-SALEABLE",
    "category": "C_TRIM"
  },
  "TM0B": const {
    "name": "BETA PRE-PRODUCTION NON-SALEABLE",
    "category": "C_TRIM"
  },
  "TM0C": const {"name": "PRE-PRODUCTION SALEABLE", "category": "C_TRIM"},
  "TP01": const {"name": "Tech Package - No Autopilot", "category": "C_OPTS"},
  "TP02": const {"name": "Tech Package with Autopilot", "category": "C_OPTS"},
  "TP03": const {
    "name": "Tech Package with Enhanced Autopilot",
    "category": "C_OPTS"
  },
  "TR00": const {"name": "No Third Row Seat", "category": "C_OPTS"},
  "TR01": const {"name": "Rear Facing Seats", "category": "C_OPTS"},
  "TRA1": const {"name": "Third Row HVAC", "category": "C_OPTS"},
  "TW01": const {"name": "Towing Package", "category": "C_OPTS"},
  "UM01": const {
    "name": "Universal Mobile Charger - US Port (Single)",
    "category": "C_OPTS"
  },
  "UTAB": const {
    "name": "Black Alcantara Headliner",
    "category": "C_INT_HEADLINER"
  },
  "UTAW": const {"name": "Light Headliner", "category": "C_INT_HEADLINER"},
  "UTPB": const {"name": "Dark Headliner", "category": "C_INT_HEADLINER"},
  "UTSB": const {"name": "Dark Headliner", "category": "C_INT_HEADLINER"},
  "WT20": const {"name": "20\" Silver Slipstream Wheels", "category": "C_WT"},
  "WTAS": const {"name": "19\" Silver Slipstream Wheels", "category": "C_WT"},
  "WTDS": const {"name": "19\" Grey Slipstream Wheels", "category": "C_WT"},
  "WTSG": const {"name": "21\" Turbine Wheels", "category": "C_WT"},
  "WTSS": const {"name": "21\" Turbine Wheels", "category": "C_WT"},
  "WTTB": const {"name": "19\" Cyclone Wheels", "category": "C_WT"},
  "WTW4": const {"name": "19\" Winter Tire Set", "category": "C_OPTS"},
  "WTW5": const {"name": "21\" Winter Tire Set", "category": "C_OPTS"},
  "WTX1": const {
    "name": "19\" Michelin Primacy Tire Upgrade",
    "category": "C_OPTS"
  },
  "WXW4": const {"name": "No 19\" Winter Tire Set", "category": "C_OPTS"},
  "WXW5": const {"name": "No 21\" Winter Tire Set", "category": "C_OPTS"},
  "X001": const {"name": "Override: Power Liftgate", "category": "C_STDEQ"},
  "X003": const {"name": "Maps & Navigation", "category": "C_STDEQ"},
  "X004": const {"name": "Override: No Navigation", "category": "C_OPTS"},
  "X007": const {"name": "Daytime running lights", "category": "C_OPTS"},
  "X010": const {"name": "Base Mirrors", "category": "C_OPTS"},
  "X011": const {"name": "Override: Homelink", "category": "C_OPTS"},
  "X012": const {"name": "Override: No Homelink", "category": "C_STDEQ"},
  "X013": const {"name": "Override: Satellite Radio", "category": "C_OPTS"},
  "X014": const {"name": "Override: No Satellite Radio", "category": "C_OPTS"},
  "X019": const {"name": "Carbon Fiber Spoiler", "category": "C_OPTS"},
  "X020": const {"name": "No Performance Exterior", "category": "C_PERF"},
  "X021": const {"name": "No Spoiler", "category": "C_OPTS"},
  "X024": const {"name": "Performance Package", "category": "C_PERF"},
  "X025": const {"name": "No Performance Package", "category": "C_PERF"},
  "X027": const {"name": "Lighted Door Handles", "category": "C_STDEQ"},
  "X028": const {"name": "Battery Badge", "category": "C_OPTS"},
  "X029": const {"name": "Remove Battery Badge", "category": "C_OPTS"},
  "X030": const {
    "name": "Override: No Passive Entry Pkg",
    "category": "C_OPTS"
  },
  "X031": const {"name": "Keyless Entry", "category": "C_STDEQ"},
  "X037": const {"name": "Powerfolding Mirrors", "category": "C_STDEQ"},
  "X039": const {"name": "DAB Radio", "category": "C_OPTS"},
  "X040": const {"name": "No DAB Radio", "category": "C_OPTS"},
  "X043": const {"name": "No Phone Dock Kit", "category": "C_OPTS"},
  "X044": const {"name": "Phone Dock Kit", "category": "C_OPTS"},
  "YF00": const {
    "name": "No Yacht Floor",
    "category": "C_INT_NOW_DEFAULT_OPTS"
  },
  "YF01": const {
    "name": "Matching Yacht Floor",
    "category": "C_INT_NOW_DEFAULT_OPTS"
  },
  "YFCC": const {"name": "YFCC", "category": "C_OPTS"},
  "YFFC": const {"name": "Integrated Center Console", "category": "C_OPTS"}
};
